/**
 * Shape of the `quieto.config.json` file written to the user's project root
 * after a successful `quieto-tokens init` run.
 *
 * The schema is intentionally **forward-compatible**: future epics add fields
 * (advanced-mode authoring, additional categories, update history) without
 * breaking existing configs. Keep it flat and well-namespaced — deep nesting
 * is harder to extend and diff.
 *
 * Related stories:
 * - Story 1.1 established the filename convention and config detection.
 * - Story 1.9 shipped v1 (inputs + overrides + output).
 * - Story 2.1 added `advanced` and `categories` (this file).
 * - Story 2.2 will push new category names into `categories`.
 * - Story 3.1 will read this file to drive diff-based re-entrant editing.
 */
export interface QuietoConfig {
  /** Optional JSON Schema URL. Reserved for future hosted schema (not MVP). */
  $schema?: string;
  /** Tool version that generated this config (from package.json). */
  version: string;
  /** ISO 8601 timestamp of generation (`new Date().toISOString()`). */
  generated: string;
  /** Quick-start prompt answers — the recipe that reproduces the token system. */
  inputs: {
    /** Brand color hex, normalized to `#RRGGBB` uppercase. */
    brandColor: string;
    /** Spacing base unit in pixels. */
    spacingBase: 4 | 8;
    /** Type-scale ratio preference. */
    typeScale: "compact" | "balanced" | "spacious";
    /** Whether both light and dark themes were generated. */
    darkMode: boolean;
  };
  /**
   * Semantic overrides the user applied in the preview step.
   *
   * Keys are semantic token names (e.g. `color.background.primary`) and
   * values are DTCG primitive references (e.g. `{color.blue.500}`).
   * Empty object when no overrides were made.
   */
  overrides: Record<string, string>;
  /** Output paths and naming used by the writer/build steps. */
  output: {
    /** Relative directory for DTCG JSON sources. Default: `"tokens"`. */
    tokensDir: string;
    /** Relative directory for built CSS. Default: `"build"`. */
    buildDir: string;
    /** CSS custom-property prefix. Default: `"quieto"`. */
    prefix: string;
  };
  /**
   * Active token categories. Epic 1 configs always generated
   * `["color", "spacing", "typography"]`; Epic 2.2's `add` subcommand will
   * push new names onto this list.
   *
   * Per ADR-001, this array is the canonical manifest — stale-output cleanup
   * diffs the on-disk file list against this array.
   */
  categories: string[];
  /**
   * Advanced-mode authoring details. `undefined` for quick-start configs.
   * Each sub-block is independently optional so the user can skip a category
   * while still supplying advanced input for another.
   */
  advanced?: AdvancedConfig;
}

/**
 * Per-category extensions collected by `init --advanced`. Only categories the
 * user customized are populated — a missing sub-block means "use the
 * quick-start defaults for this category".
 */
export interface AdvancedConfig {
  color?: AdvancedColorConfig;
  spacing?: AdvancedSpacingConfig;
  typography?: AdvancedTypographyConfig;
}

export interface AdvancedColorConfig {
  /**
   * Additional hue ramps beyond the primary brand hue. Each entry gets its
   * own seed hex fed to `@quieto/engine`, producing a full 50–900 ramp.
   *
   * `name` is the semantic role (`accent`, `error`, ...) or a user-defined
   * label; `seed` is a `#RRGGBB` hex. Order matters for preview ordering.
   */
  additionalHues: Array<{
    name: string;
    seed: string;
  }>;
}

export interface AdvancedSpacingConfig {
  /**
   * Overrides for individual spacing steps. Keys match the primitive token
   * names generated by the spacing ramp (`"space-4"`, `"space-6"` …); values
   * are the desired pixel count for that step. Omitted keys fall back to the
   * preset-derived value.
   */
  customValues: Record<string, number>;
}

export interface AdvancedTypographyConfig {
  /** Font-family stacks per role. `undefined` means "use default stack". */
  fontFamily?: {
    heading?: string;
    body?: string;
    mono?: string;
  };
  /** Per-role size override in pixels (e.g. `{"font-size-lg": 18}`). */
  customSizes?: Record<string, number>;
  /** Per-role weight override (CSS numeric, 100–900). */
  customWeights?: Record<string, number>;
  /** Line-height overrides (unitless multiplier). */
  lineHeight?: {
    heading?: number;
    body?: number;
  };
  /** Letter-spacing overrides (CSS length token, e.g. `"-0.02em"`). */
  letterSpacing?: {
    heading?: string;
    body?: string;
  };
}

/**
 * Default output paths — kept in one place so writer + config stay in sync.
 * Frozen so an importer that mutates it cannot poison subsequent
 * `buildConfig` calls.
 */
export const DEFAULT_OUTPUT_CONFIG: Readonly<QuietoConfig["output"]> =
  Object.freeze({
    tokensDir: "tokens",
    buildDir: "build",
    prefix: "quieto",
  });

/**
 * Canonical list of core categories generated by quick-start. Stored as a
 * frozen tuple so legacy-config fallback paths can share one reference.
 */
export const DEFAULT_CATEGORIES: readonly string[] = Object.freeze([
  "color",
  "spacing",
  "typography",
]);
