import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { QuietoConfig } from "../types/config.js";

export const CONFIG_FILENAME = "quieto.config.json";

export function getConfigPath(cwd: string = process.cwd()): string {
  return resolve(cwd, CONFIG_FILENAME);
}

export function configExists(cwd: string = process.cwd()): boolean {
  return existsSync(getConfigPath(cwd));
}

export interface LoadConfigOptions {
  /**
   * The current tool version. When provided, `loadConfig` logs a warning via
   * `console.warn` if the file records a *newer* version than the running
   * tool (forward-incompatible scenario). Falsy/missing → skip the check.
   */
  toolVersion?: string;
}

/**
 * Compare two dot-separated semver-like version strings. Returns a negative
 * number if `a < b`, positive if `a > b`, `0` if equal. Non-numeric segments
 * and trailing pre-release tags are ignored — this is deliberately coarse so
 * a generated config is only flagged when the numeric major/minor/patch is
 * strictly higher than the tool's own version.
 */
function compareVersions(a: string, b: string): number {
  const parse = (v: string): number[] =>
    v
      .split("-")[0]!
      .split(".")
      .map((segment) => {
        const n = Number.parseInt(segment, 10);
        return Number.isFinite(n) ? n : 0;
      });

  const av = parse(a);
  const bv = parse(b);
  const len = Math.max(av.length, bv.length);
  for (let i = 0; i < len; i++) {
    const diff = (av[i] ?? 0) - (bv[i] ?? 0);
    if (diff !== 0) return diff;
  }
  return 0;
}

/**
 * Read and parse an existing `quieto.config.json` from the given directory.
 *
 * Returns `null` when the file doesn't exist or cannot be parsed as a valid
 * config (missing required `version` field, malformed JSON). Callers that
 * need the raw read error can catch above this; this function is designed
 * for the happy "does this look like a quieto config we can work with?"
 * path that drives re-entrant editing in Epic 3.
 *
 * When {@link LoadConfigOptions.toolVersion} is supplied and the config's
 * `version` is *newer* than the tool's, a `console.warn` is emitted but the
 * config is still returned — the caller decides whether to proceed.
 */
export function loadConfig(
  cwd: string = process.cwd(),
  options: LoadConfigOptions = {},
): QuietoConfig | null {
  const filePath = getConfigPath(cwd);

  let raw: string;
  try {
    raw = readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }

  // Strip a leading UTF-8 BOM (some Windows editors save JSON with one);
  // JSON.parse rejects it but the file is otherwise valid.
  if (raw.charCodeAt(0) === 0xfeff) {
    raw = raw.slice(1);
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }

  if (
    typeof parsed !== "object" ||
    parsed === null ||
    typeof (parsed as { version?: unknown }).version !== "string"
  ) {
    return null;
  }

  const config = parsed as QuietoConfig;

  if (
    options.toolVersion &&
    compareVersions(config.version, options.toolVersion) > 0
  ) {
    console.warn(
      `quieto.config.json was generated by a newer version of quieto-tokens (${config.version}) than the one currently installed (${options.toolVersion}). Some fields may not be understood.`,
    );
  }

  return config;
}
